<a href="https://colab.research.google.com/github/yihaozhong/479_data_management/blob/main/CS_479_midterm_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ed Exercise

Write a list comprehension that creates a list of all the squares of the numbers from 1 to 20.

In [ ]:
squares=[x*x for x in range(1,21)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


## Ed Exercise

Write a dictionary comprehension that creates a dictionary with keys from 1 to 20 and values which are the squares of the keys.

In [ ]:
squaresDict={x:x*x for x in range(1,21)}
print(squaresDict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400}


## Ed Exercise

Use the following appproach to find the first 20 prime numbers. In this approach, you start with a list of primes consisting just of the number 2. You then try subsequent numbers, starting with 3 and see if they are divisible by any of the numbers that are on the current list of primes. If they aren't, you add them to the list of primes. This minimizes the number of integer divisions you need to do.

In [ ]:
primes=[2]
i=3
while (len(primes)<20):
  isPrime=True
  for divisor in primes:
    if (i%divisor)==0:
      isPrime=False
      break
  if isPrime: 
    primes.append(i)      
  i+=1
print(primes)  


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]


##Ed Exercise

Write a generator for primes, called genPrime, based on the code you just wrote.The first time the generator is called, it should return 2, the next time, 3, etc.

Your function should yield up an unlimited number of primes. Use the next method to print out the first 20.

In [ ]:
def genPrime():
  yield 2
  primes=[2]
  i=3
  while True:
    isPrime=True
    for divisor in primes:
     if (i%divisor)==0:
       isPrime=False
       break
    if isPrime: 
      primes.append(i)      
      yield i
    i+=1

p=genPrime()
for i in range(20):   
  print(next(p),"",end="")
print()  


2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 


## Ed Exercise

Use Python to open the countries.csv file which is found here:

https://drive.google.com/drive/folders/1-GKCGczNYt_4hBECuNBytOPX7QXBxBVS?usp=sharing

Using ordinary Python file operations (no CSV module or Pandas), read the country and population into a dictionary where the country is the key and the population is the value. If the population is blank, put a zero.

Then use a dictionary comprehension to create another dictionary with only those countries that have a population over 100 million. How many are there? What is their average population?

In [ ]:
f=open("/content/drive/MyDrive/0479 Spring 2022/data/countries.csv","r")
next(f)
pops={}
for line in f:
    values=line.split(",")
    try:
        pops[values[0]]=float(values[3])
    except:
        pops[values[0]]=0
#print(pops)
highpops={country:population for country,population in pops.items() if population>100000000}
print(highpops)
print(len(highpops))
print(sum(highpops.values())/len(highpops))

{'United States': 332566652.0, 'Japan': 125340000.0, 'Russia': 145478097.0, 'Mexico': 126014024.0, 'China': 1412600000.0, 'Brazil': 214389640.0, 'Egypt': 103053315.0, 'Indonesia': 272248500.0, 'Philippines': 111628046.0, 'India': 1374305400.0, 'Pakistan': 225200000.0, 'Bangladesh': 172388884.0, 'Nigeria': 211401000.0, 'Ethiopia': 117876000.0}
14
353177825.5714286


## Ed Exercise

Use numpy to create a 10 by 10 array which is all zeroes, and then "frame" it with a border of ones.

In [ ]:
import numpy as np
x=np.zeros((10,10))
x[0]=1
x[9]=1
x[:,0]=1
x[:,9]=1
x


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
x=np.ones((10,10))
x[1:9,1:9]=0
x



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ed Exercise

Create a 4 by 4 identify matrix with numpy. An identity matrix has zeros everywhere except the diagonal, where it has ones.

In [ ]:
x=np.zeros((4,4))
for i in range(4):
  x[i,i]=1
x  

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
x=np.identity(4)
x


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Ed Exercise

Create a ndarray from the list [1,2,3,4]. Then matrix multiply that ndarray by the 4 by 4 identity matrix you created. You should get the [1,2,3,4] ndarray back.

In [ ]:
y=np.asarray([1,2,3,4])
y.dot(x)
x.dot(y)

array([1., 2., 3., 4.])

In [ ]:
x@y

array([1., 2., 3., 4.])

In [ ]:
y@x

array([1., 2., 3., 4.])

## Ed Exercise

The following 5 by 5 array is a ["magic square"](https://en.wikipedia.org/wiki/Magic_square) in that all of its rows, columns, and its two longest (main) diagonals all add up to a single number (in this case, 65). 

Use numpy to verify this. Hint: the numpy methods diag and fliplr will be helpful here.

Then reset the "21" in the array to "22" and verify it is no longer a magic square.

In [ ]:
A=np.array([[17, 24, 1, 8, 15], 
            [23, 5, 7, 14, 16], 
            [ 4, 6, 13, 20, 22], 
            [10, 12, 19, 21, 3],
            [11, 18, 25, 2, 9]])

In [ ]:
print(A.sum(axis=0))
print(A.sum(axis=1))
print(np.diag(A))
print(np.diag(A).sum())
print(np.diag(np.fliplr(A)))
np.diag(np.fliplr(A)).sum()

[65 65 65 65 65]
[65 65 65 65 65]
[17  5 13 21  9]
65
[15 14 13 12 11]


65

In [ ]:
A[3,3]=22
print(A)

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 22  3]
 [11 18 25  2  9]]


In [ ]:
print(A.sum(axis=0))
print(A.sum(axis=1))

[65 65 65 66 65]
[65 65 65 66 65]


## Ed Exercise

Turn the following row vector to a column vector.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [ ]:
y=x.reshape(8,1)
print(y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
y.shape

(8, 1)

## Ed Exercise

Create a 4x4 numpy array in which each row contains the numbers [1,2,3,4] by using broadcasting.

In [ ]:
y=np.zeros((4,4))
y=y+np.array([1,2,3,4])
y

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## Ed Exercise

Create a numpy array of ones. Then set the eighth column to all 2s, the ninth to all 3s, and the tenth to all 4s.

In [ ]:
y=np.ones((10,10))
y[:,7:]=[2,3,4]
y

array([[1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.],
       [1., 1., 1., 1., 1., 1., 1., 2., 3., 4.]])

## Ed Exercise

Using the countries.csv file in here:

https://drive.google.com/drive/folders/1-GKCGczNYt_4hBECuNBytOPX7QXBxBVS?usp=sharing

Create a dataframe consisting of two columns, country and population, restricted just to the countries with population over 100,000,000. How many countries are there? What is the average population of these countries?

In [ ]:
import pandas as pd
countries=pd.read_csv("/content/drive/MyDrive/0479 Spring 2022/data/countries.csv")
highpop=countries[countries['population']>100000000][['country','population']]
highpop=highpop.sort_values(by='population', ascending=False)
print(highpop.describe())
highpop.head(30)

         population
count  1.400000e+01
mean   3.531778e+08
std    4.457841e+08
min    1.030533e+08
25%    1.255085e+08
50%    1.918949e+08
75%    2.604864e+08
max    1.412600e+09


country    population
74           China  1.412600e+09
127          India  1.374305e+09
7    United States  3.325667e+08
100      Indonesia  2.722485e+08
134       Pakistan  2.252000e+08
83          Brazil  2.143896e+08
143        Nigeria  2.114010e+08
136     Bangladesh  1.723889e+08
54          Russia  1.454781e+08
71          Mexico  1.260140e+08
29           Japan  1.253400e+08
164       Ethiopia  1.178760e+08
120    Philippines  1.116280e+08
98           Egypt  1.030533e+08

## Ed Exercise

The Gini coefficient is a measure of income inequality in a country. It ranges from perfect equality (0) to maximal inequality (100). 

Use the countries database to find the country with the highest Gini coefficient on each continent. Create a small dataframe consisting of three columns: country, continent, and gini with just one row per continent containing the highest-Gini countries.

In [ ]:
countries=pd.read_csv("/content/drive/MyDrive/0479 Spring 2022/data/countries.csv")
g=countries[['country','continent','gini']].dropna()
g=g.sort_values(by=['continent','gini'],ascending=False)
g=g.drop_duplicates(['continent'])
print(g.head(50))

             country continent  gini
160       Micronesia   Oceania  61.1
78   North Macedonia    Europe  43.6
9          Hong Kong      Asia  53.9
165            Haiti  Americas  60.8
167          Lesotho    Africa  63.2


## Ed Exercise

Put the countries into bins of per-capita GDP with breakpoints at every \$10,000. So the bins are \$0-10K, \$10-20K, all the way up to the range containing the maximum per capita GDP in the table. Output a table of the number of countries in each bin.

In [ ]:
countries=pd.read_csv("/content/drive/MyDrive/0479 Spring 2022/data/countries.csv")
maxGDP=countries['gdpPerCapita2021'].max()
print(maxGDP)
width=10000
bins=list(range(0,int(maxGDP)+width,width))
pd.cut(countries['gdpPerCapita2021'],bins).value_counts()

122740.0


(0, 10000]          78
(10000, 20000]      45
(20000, 30000]      19
(40000, 50000]      15
(30000, 40000]      14
(50000, 60000]      11
(60000, 70000]       7
(90000, 100000]      3
(70000, 80000]       1
(100000, 110000]     1
(120000, 130000]     1
(80000, 90000]       0
(110000, 120000]     0
Name: gdpPerCapita2021, dtype: int64

## Ed Exercise

Estimate the GDP of each country by multiplying the GDP per capita column by the population column to create a new column. Then create a new dataframe consisting of the country names and the GDPs of the countries beginning with an "S". Drop the rows containing missing rows from this dataframe. 

In [ ]:
countries=pd.read_csv("/content/drive/MyDrive/0479 Spring 2022/data/countries.csv")
countries['gdp']=countries['gdpPerCapita2021']*countries['population']
sCountries=countries[(countries['country'].str[0]=="S")][['country','gdp']].sort_values(by='gdp',ascending=False)
sCountries=sCountries.dropna()
sCountries.head(50)

country           gdp
27                        South Korea  2.427795e+12
35                              Spain  1.966235e+12
25                       Saudi Arabia  1.684110e+12
103                      South Africa  7.482989e+11
5                         Switzerland  6.614539e+11
18                             Sweden  5.807939e+11
1                           Singapore  5.603138e+11
92                          Sri Lanka  3.081678e+11
44                           Slovakia  1.898123e+11
152                             Sudan  1.807286e+11
70                             Serbia  1.411759e+11
130                             Syria  1.164729e+11
37                           Slovenia  8.608844e+10
158                           Senegal  6.243518e+10
192                           Somalia  1.539476e+10
183                      Sierra Leone  1.469555e+10
193                       South Sudan  1.093119e+10
88                           Suriname  8.792394e+09
57                         Seychelles  2.591057e+09
91                        Saint Lucia  2.491380e+09
10                         San Marino  2.071897e+09
172                   Solomon Islands  1.807726e+09
102  Saint Vincent and the Grenadines  1.418126e+09
67              Saint Kitts and Nevis  1.119420e+09
145                             Samoa  1.051227e+09
154             São Tomé and Príncipe  8.425589e+08